---
inherit_from:
  - .rubocop_todo.yml
inherit_gem:
  rubocop-rake: config/default.yml
  rubocop-rspec: config/default.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml
  standard: config/base.yml
inherit_mode:
  merge:
    - Exclude
plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-thread_safety
require:
  - standard
  - standard-custom
  - standard-performance
AllCops:
  NewCops: enable
#  TargetRailsVersion: <%= `rails -v`.split.last %>
  TargetRubyVersion: <%= File.read(".ruby-version").strip %>
Layout/LineLength:
  Enabled: true
  Exclude:
    - bin/bundle
    - db/schema.rb
  Max: 120
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  Exclude:
    - db/schema.rb
