---
exclude:
  - ".bundle/**/*"
  - "coverage/**/*"
  - "db/*.sqlite3"
  - "log/**/*"
  - "node_modules/**/*"
  - "public/**/*"
  - "storage/**/*"
  - "tmp/**/*"
  - "vendor/bundle/**/*"
include:
  - "**/*.rb"
max_files: 5000
plugins:
  - solargraph-rails
  - solargraph-rubocop
  - solargraph-standardrb
reporters:
  - require_not_found
  - rubocop
  - standardrb
  - typecheck
  - update_errors
