_primary_database: &primary_database
  adapter: postgresql
  database: primary_database
  encoding: unicode
  pool: <%= ProjectConfigHelper.database_pool %>
  url: <%= ENV.fetch("DATABASE_URL") %>
  variables:
    lock_timeout: <%= ENV.fetch("DATABASE_LOCK_TIMEOUT", 3000) %>

_with_primary_replica: &with_primary_replica
  primary:
    <<: *primary_database
  primary_replica:
    <<: *primary_database
    replica: true
    url: <%= ENV.fetch("DATABASE_URL_READONLY") %>

development:
  <<: *with_primary_replica

test:
  <<: *with_primary_replica

staging:
  <<: *with_primary_replica

production:
  <<: *with_primary_replica
